version: "3"
services:
    nodeServer:
        image: docker-node-express-mongoapp
        build: ./
        command: npm run serve
        ports: 
          -"50051:50051"
        volumes: 
          -./:/usr/src/app
          -/usr/src/app/node_modules
        depends_on:
          -"serpsDataStore"
    serpsDataStore:
        image: "mongo"
        ports: 
          -"27017:27017"

    adminMongo:
      image: "mrvautin/adminmongo"
      ports:
        -"1234:1234"